### PR TITLE
[Refactor] Updated Launch Parameters

### PR DESCRIPTION
**Pull request by jpeng-ms**
## Purpose
refactored launch parameters into - local, remote and localization options.

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by Mrayyan — CHANGES_REQUESTED** [review]
@jpeng-ms The android bridging guide page also needs to be updated

**Review by palatter — DISMISSED** [review]
Looks good.

**Comment by palatter** [comment]
> @jpeng-ms The android bridging guide page also needs to be updated

@jpeng-ms Is there iOS documentation that needs to be updated along with this?

**Comment by Mrayyan** [comment]
> > @jpeng-ms The android bridging guide page also needs to be updated
> 
> @jpeng-ms Is there iOS documentation that needs to be updated along with this?

yes, the iOS one should be updated as well.

**Comment by jpeng-ms** [comment]
> > > @jpeng-ms The android bridging guide page also needs to be updated
> > 
> > 
> > @jpeng-ms Is there iOS documentation that needs to be updated along with this?
> 
> yes, the iOS one should be updated as well.

updated for android, but I don't see any reference of launch parameters under iOS, are you talking about MSDoc?

**Review by Mrayyan — APPROVED** [review]

**Comment by Mrayyan** [comment]
> > > > @jpeng-ms The android bridging guide page also needs to be updated
> > > 
> > > 
> > > @jpeng-ms Is there iOS documentation that needs to be updated along with this?
> > 
> > 
> > yes, the iOS one should be updated as well.
> 
> updated for android, but I don't see any reference of launch parameters under iOS, are you talking about MSDoc?

No your are right. I thought there was reference in the iOS page. PR looks good 👍

**Review by JoshuaLai — APPROVED** [review]

**Pull request merged**
