### PR TITLE
[Feature] Added Support for Title and Subtitle

### PR DESCRIPTION
**Pull request by jpeng-ms**
## Purpose
added support for 1.1.0 features

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by Mrayyan** [comment]
Can you update this new title and subtitle info in the read me as well.

**Review by Mrayyan — APPROVED** [review]
lgtm 👍

**Comment by JoshuaLai** [comment]
Tested and everything is working as expected. 
The launch method is getting rather larger we need a refactor task to clean all this up

**Review by JoshuaLai — APPROVED** [review]

**Comment by jpeng-ms** [comment]
Thanks, just created a new task under KTLO and I will be working on it next sprint

**Pull request merged**
